#!/usr/bin/env python
"""
Keep AI authorship out of the git history: trailers, footers, "generated by".

OPT-IN. Nothing runs this by default — the template takes no position on whether
AI attribution belongs in your history. Turn it on when your project's answer is
"no", by uncommenting the `no-ai-attribution` hook in .pre-commit-config.yaml
and the matching CI step in .github/workflows/ci.yml. See docs/conventions.md.

Why a script rather than a line in the contributor guide: coding agents are
frequently instructed by their own harness to append `Co-Authored-By` and a
"Generated with …" footer to every commit. A written rule competes with that
instruction and loses eventually; a hook does not.

Modes:
    check_no_ai_attribution.py .git/COMMIT_EDITMSG   # commit-msg hook
    check_no_ai_attribution.py --text "<text>"       # PR body in CI

Deliberately NOT flagged: mentions that are names rather than signatures —
`CLAUDE.md`, a `docs(claude)` scope, `.claude/` paths, or a model identifier in
the subject of a commit that integrates it (`feat(ai): pricing for gpt-5`).
A gate that fails on those gets disabled with the first `--no-verify`, and then
it catches nothing at all.
"""

from __future__ import annotations

import re
import sys

# Paths, scopes and artefacts where the vendor name is part of a filename.
SAFE_TOKENS = re.compile(
    r"""
    CLAUDE\.md
    | AGENTS\.md
    | \.claude/[\w./-]*
    | docs\(claude\)
    """,
    re.IGNORECASE | re.VERBOSE,
)

# Model identifiers are legitimate in the subject of an integration commit, so
# they are stripped before the trailer check — but only after the authorship
# check, so "Generated by claude-opus-5" is still a violation.
MODEL_IDS = re.compile(
    r"\b(claude|gpt|gemini|llama|mistral)[-\s](opus|sonnet|haiku|fable|[\d.]+)[-\s]?[\w.]*",
    re.IGNORECASE,
)

AI_NAMES = r"claude|anthropic|openai|chatgpt|copilot|gemini|cursor"

# A trailer line: `Key: value` at the end of a message. Scope prefixes such as
# `docs(claude):` do not match (parentheses), so commit subjects are unaffected.
TRAILER = re.compile(r"^([A-Za-z][A-Za-z-]*):\s*(.*)$")

AUTHORSHIP = [
    (
        re.compile(
            rf"\b(generated|authored|written|created|assisted)\s+(with|by)\b[^\n]*"
            rf"\b({AI_NAMES}|opus|sonnet|haiku|fable)\b",
            re.IGNORECASE,
        ),
        'authorship footer ("Generated with/by …")',
    ),
    (
        re.compile(r"noreply@(anthropic|openai)\.com", re.IGNORECASE),
        "vendor noreply address",
    ),
    (
        re.compile(r"claude\.(ai|com)/(code|claude-code)", re.IGNORECASE),
        "link to the assistant's product page",
    ),
]

SCISSORS = ">8"


def strip_git_noise(raw: str) -> str:
    """
    Drop git's own hints and the diff appended by `commit.verbose=true`.

    Without this the gate fails on the very commit that edits this file: the
    diff literally contains the text of a forbidden trailer.
    """
    lines: list[str] = []
    for line in raw.splitlines():
        if line.startswith("#") and SCISSORS in line:
            break
        if line.startswith("#"):
            continue
        lines.append(line)
    return "\n".join(lines)


def find_violations(message: str) -> list[str]:
    """Return descriptions of the AI signatures found (empty list means clean)."""
    text = SAFE_TOKENS.sub("", strip_git_noise(message))
    violations: list[str] = []

    for pattern, label in AUTHORSHIP:
        for match in pattern.finditer(text):
            violations.append(f"{label}: {match.group(0).strip()}")

    without_models = MODEL_IDS.sub("", text)
    for line in without_models.splitlines():
        trailer = TRAILER.match(line.strip())
        if not trailer:
            continue
        if re.search(AI_NAMES, trailer.group(1) + trailer.group(2), re.IGNORECASE):
            violations.append(f"trailer crediting an AI: {line.strip()}")

    return violations


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)

    if argv and argv[0] == "--text":
        message = argv[1] if len(argv) > 1 else ""
        source = "text"
    elif argv:
        message = open(argv[0], encoding="utf-8").read()
        source = argv[0]
    else:
        print("Usage: check_no_ai_attribution.py <file> | --text <text>")
        return 2

    violations = find_violations(message)
    if not violations:
        return 0

    print(f"AI authorship is not allowed in git history, found in {source}:")
    for violation in violations:
        print(f"  • {violation}")
    print(
        "\nRemove the signature and try again. Mentioning `CLAUDE.md`, `.claude/` "
        "or a model identifier in a commit subject is fine."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
