"""
Tests for the opt-in AI-attribution gate (scripts/check_no_ai_attribution.py).

The gate is off by default, but it is still tested: a regex that fails on
ordinary commit messages gets bypassed with `--no-verify` the first time it
misfires, and then it protects nothing.
"""

import importlib.util
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parents[3] / "scripts" / "check_no_ai_attribution.py"

spec = importlib.util.spec_from_file_location("check_no_ai_attribution", SCRIPT)
gate = importlib.util.module_from_spec(spec)
spec.loader.exec_module(gate)


@pytest.mark.parametrize(
    "message",
    [
        "feat(catalog): add entity search\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
        "fix: correct totals\n\n🤖 Generated with Claude Code",
        "docs: update readme\n\nGenerated by ChatGPT",
        "chore: bump deps\n\nAssisted-By: Copilot",
        "fix: patch\n\nSee https://claude.ai/code/session_123",
    ],
)
def test_signatures_are_rejected(message):
    assert gate.find_violations(message)


@pytest.mark.parametrize(
    "message",
    [
        "feat(accounts): add profile page",
        "docs(claude): document the routing table in CLAUDE.md",
        "chore: move the session hook into .claude/hooks/",
        "feat(ai): add pricing for claude-opus-5",
        "fix: handle gpt-5 rate limits",
        "refactor: extract selectors\n\nReviewed-by: Jane Doe <jane@example.com>",
    ],
)
def test_legitimate_messages_pass(message):
    assert gate.find_violations(message) == []


def test_verbose_commit_diff_is_ignored():
    # `commit.verbose=true` appends the diff below a scissors line; the diff of
    # this very file contains the forbidden strings.
    message = (
        "docs: document the gate\n"
        "# ------------------------ >8 ------------------------\n"
        "+Co-Authored-By: Claude <noreply@anthropic.com>\n"
    )
    assert gate.find_violations(message) == []


def test_git_comment_lines_are_ignored():
    message = "feat: thing\n# Please enter the commit message for your changes.\n"
    assert gate.find_violations(message) == []
